### Get all
GET http://localhost:3000/api/players

### Get single
GET http://localhost:3000/api/players/1


### Create new
POST http://localhost:3000/api/players
Content-Type: application/json; charset=utf-8

{
  "name": "Stefan",
  "jersey": 2,
  "age": 51,
  "id": 1
}